export enum AIIntent {
  CHECK_BALANCE = "CHECK_BALANCE",
  FAILED_PURCHASE = "FAILED_PURCHASE",
  RETRY_PURCHASE = "RETRY_PURCHASE",
  FUND_WALLET = "FUND_WALLET",
  TOKEN_ISSUE = "TOKEN_ISSUE",
  GENERAL_QUESTION = "GENERAL_QUESTION",
}
